name: Super-Linter # Baris 29
on: push # Baris 30 (Workflow berjalan saat ada 'push' ke repo)

jobs:
  super-lint: # Baris 31
    runs-on: ubuntu-latest # Baris 33
    steps:
      - name: Checkout code # Baris 34
        uses: actions/checkout@v2 # Baris 35

      - name: Run Super-Linter # Baris 36
        uses: github/super-linter@v4 # Baris 37
        env: # Baris 43
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Baris 45 (Ini adalah secret default GitHub)
          # Anda juga dapat menambahkan variabel ENV_TO_PASS jika diperlukan, seperti:
          # DEFAULT_BRANCH: master
